//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giaibai2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
        [DisplayName("Mã Sản Phẩm")]
        public string MaSanPham { get; set; }

        [DisplayName("Tên Sản Phẩm")]
        [RegularExpression("^[a-zA-Z].*", ErrorMessage = "Ký tự đầu tiên phải là chữ cái.")]
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string TenSanPham { get; set; }

        [DisplayName("Mã Phân Loại")]
        public string MaPhanLoai { get; set; }

        [RegularExpression(@"^\d+$", ErrorMessage = "Vui lòng nhập số")]
        [DisplayName("Giá Nhập")]
        public Nullable<long> GiaNhap { get; set; }

        [RegularExpression(@"^\d+$", ErrorMessage = "Vui lòng nhập số")]
        [DisplayName("Đơn Giá Bán Nhỏ Nhất")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }

        [RegularExpression(@"^\d+$", ErrorMessage = "Vui lòng nhập số")]
        [DisplayName("Đơn Giá Bán Lớn Nhất")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }

        [DisplayName("Trạng Thái")]
        public Nullable<bool> TrangThai { get; set; }

        [DisplayName("Mô Tả Ngắn")]
        [RegularExpression("^[a-zA-Z].*", ErrorMessage = "Ký tự đầu tiên phải là chữ cái.")]
        public string MoTaNgan { get; set; }

        [DisplayName("Ảnh Đại Diện")]
        [RegularExpression(@".*\.(jpg)$", ErrorMessage = "Ảnh đại diện phải có định dạng 'jpg'")]
        public string AnhDaiDien { get; set; }

        [DisplayName("Nổi Bật")]
        public Nullable<bool> NoiBat { get; set; }

        [DisplayName("Mã Phân Loại Phụ")]
        public string MaPhanLoaiPhu { get; set; }

        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }

        [DisplayName("Sản Phẩm Theo Màu")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }

    }
}
